### ISSUE TITLE
Please consider renaming the repository to something less generic

### ISSUE THREAD

**Issue by unixorn** [gsalami00/softblobby#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but the name is awfully generic. Please consider renaming it to something descriptive, or even just name it `softblobby` to match the file name of the theme file.

Thanks!

**Comment by gsalami00** [comment]
@unixorn Done! Here's the [link](https://github.com/gsalami00/softblobby). Thank you!
